### ISSUE TITLE
google assistant does not react with the hotwords

### ISSUE THREAD

**Issue by guzzler13** [eouia/MMM-AssistantMk2#24] opened 2018-09-25 20:02 UTC
Hi, first of all thank you for this project!
I managed to install everything without much problem, everything is configured as I want. I received my microphone today so I wanted to test mmm-assitant-mk2. I installed it, I also installed mmm-hotword and MMM-NotificationTrigger. The application runs normally but when I say "snowboy" or "magic mirror" nothing happens. Yet the microphone works well I tested it with:

arecord -D plughw: 1.0 -d 3 test.wav && aplay test.wav

I can hear the return of my voice. If anyone has an idea to help me progress ... Thank you!

**Comment by guzzler13** [comment] 2018-09-25 20:03
`pi@magicMirror:~/MagicMirror $ npm start

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: MMM-GoogleTasks
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-NotificationTrigger
Connecting socket for: MMM-Hotword
MMM-Hotword started
Connecting socket for: MMM-AssistantMk2
MMM-AssistantMk2 started
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-GoogleTasks
Starting node helper for: MMM-GoogleTasks
Connecting socket for: MMM-NowPlayingOnSpotify
Sockets connected & modules started ...
Launching application.
MMM-NotificationTrigger received a socket notification: INIT - Payload: [object Object]
[HOTWORD] begins listening.`

**Comment by eouia** [comment] 2018-09-26 07:02
Your error logs (is it broken?) shows no error as your words.
Test `MMM-Hotword` alone by disabling all other modules in your config.
We should know where the problem is coming from.

**Comment by guzzler13** [comment] 2018-09-26 07:37
Ok I tried this and the screen is totally black, but no errors in the error logs :

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
[HOTWORD] begins listening.

**Comment by eouia** [comment] 2018-09-26 07:40
`[HOTWORD] begins listening.` means the module works without problem and is waiting your voice.
Try `smart mirror`, `jarvis` or `snowboy`. If you are not a native English speaker, some exercise might be needed.

**Comment by eouia** [comment] 2018-09-26 07:44
You can test whether your `MMM-Hotword` is REALLY listening your voice by modifying this code.
https://github.com/eouia/MMM-Hotword/blob/master/node_helper.js#L71
In line 71 of node_helper.js of MMM-Hotword, modify like this;
```
 detector
      .on('silence', ()=>{
        console.log("silence")
      })
      .on('sound', (buffer)=>{
        console.log("sound")
      })
...
```

**Comment by guzzler13** [comment] 2018-09-26 07:47
ok i try this

**Comment by guzzler13** [comment] 2018-09-26 08:01
. ok you're right, **MMM-Hotword**  is not listening my voice, no console.log appears

**Comment by guzzler13** [comment] 2018-09-26 08:05
but when i try this :

arecord -D plughw:1,0 -d 3 test.wav && aplay test.wav

I hear my voice.

**Comment by guzzler13** [comment] 2018-09-26 08:38
ok it's better thanks !! but now I have this error :

[HOTWORD] <<  snowboy  >> is detected.
[HOTWORD] stops listening
assistant ready
Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:614:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1110:18
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Service unavailable.' }
[HOTWORD] begins listening.

**Comment by eouia** [comment] 2018-09-26 08:41
There is the same field(`record.device`) in your `MMM-AssistantMk2`. Set it as `plughw:1,0` or `plughw:1`.
I made these modules for `DEFAULT` devices, so you should set your `SPECIFIC` device name if your device is not `DEFAULT`.

**Comment by guzzler13** [comment] 2018-09-26 08:50
ok you're a boss !!! thank you ;-) it's perfect and in french :-D... now i'm going to look for how to turn on and off the mirror with the voice

**Comment by eouia** [comment] 2018-09-26 08:51
Nice to you. I'll close this issue. Have a nice day.

**Closed by eouia** 2018-09-26 08:51 UTC

**Comment by chino-lu** [comment] 2018-10-02 16:54
none of this is working for me... hotword and assistant are not triggered

but
arecord -D plughw:1,0 -d 3 test.wav && aplay test.wav
is working perfectly for me

**Comment by Redbull2515** [comment] 2020-02-19 22:29
q
