### ISSUE TITLE
Service Unavailable after two attemps

### ISSUE THREAD

**Issue by idmarco** [eouia/MMM-AssistantMk2#83] opened 2019-02-06 11:45 UTC
First of all, thanks for everything
After installing MMM-AssistantMk2 and MMM-Hotword works correctly one or two times, but then the following error appears:
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:614:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1110:18
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Service unavailable.' }

Then I need restart the magicMirror
I have tried with grpc-js and with grpc-1.13
My config file:
{
      module: "MMM-AssistantMk2",
      position: "lower_third",
      config: {
        useWelcomeMessage: "",
        responseVoice: true, // If available, Assistant will response with her voice.
        responseScreen: true, // If available, Assistant will response with some rendered HTML
        responseAlert: false, // If available, Assistant will response with Alert module of MM
        screenDuration: 0, // milliseconds. How long responseScreen will be shown after speech.
        record: {
        		sampleRate    : 16000,      // audio sample rate
        		threshold     : 0.5,        // silence threshold (rec only)
        		thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
        		thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
        		silence       : 1.0,        // seconds of silence before ending
        		verbose       : true,      // log info to the console
        		recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
        		device        : "plughw:1,0"        // recording device (e.g.: "plughw:1") <-----------------------------
        },
  
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
      }
    },
    {
      module: "MMM-Hotword",
      config: {
        record: {
          sampleRate    : 16000,      // audio sample rate
          threshold     : 0.5,        // silence threshold (rec only)
          thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
          thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
          silence       : 1.0,        // seconds of silence before ending
          verbose       : true,      // log info to the console. Use this when you want to check mic working or not.
          recordProgram : 'arecord',  // Defaults to 'arecord' - also supports 'rec' and 'sox'
          device        : "plughw:1,0",
        },
        snowboy:[
          {
            file: 'resources/models/Jarvis_N.pmdl',
            sensitivity: '0.8',
            hotwords: ['jarvis'] 
          }
        ],
        autostart:true,
        onDetected: {
          notification: function (payload) {
            return "ASSISTANT_ACTIVATE"
          },
          payload: function (payload){
            return {
              profile: payload.hotword
            }
          }
        },
      },

Thanks for your help!

**Comment by eouia** [comment] 2019-02-06 13:22
service unavailable error usually come from your recording device setup fails. `plughw:1,0` is the right setup to activate your recording device?

**Comment by idmarco** [comment] 2019-02-06 14:53
Thanks for your reply.
Yes, even though my MIC is USB. What's wrong is that it works once or twice and then fails.

pi@magicpiHost:~ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: AK5371 [AK5371], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

My .asoundrc is the same as /etc/asound.conf:
pcm.!default {
        type asym
        capture.pcm "mic"
        playback.pcm "speaker"
}
pcm.mic {
        type plug slave { pcm "hw:1,0" }
}
pcm.speaker {
        type plug
        slave.pcm {
                type bluealsa device "00:15:33:06:23:5F"
                profile "a2dp"
        }
}
ctl.!default {
        type bluealsa
}

Regards!

**Comment by eouia** [comment] 2019-02-06 14:57
Very weird error. After one or two normal working, then being failure, I cannot imagine what could make this symptom at this moment. sorry. When once failure happens, Have you tried Restarting MM without reboot? It still had same problem?

**Comment by idmarco** [comment] 2019-02-06 15:07
Yes, when the error appears, restart MM with pm2 restart magicMirror. I have also restarted raspberry.
I also think it's a weird mistake
Do you want me to send you logs of some kind?

Thanks for all

**Comment by eouia** [comment] 2019-02-06 15:08
Sure. My email is eouia0819@gmail.com or Telegram : @eouia
And try to check Mic working on console after failure.

**Comment by idmarco** [comment] 2019-02-06 15:12
When the error appear i try in another console:
pi@magicpiHost:~ $ rec test.wav
rec FAIL formats: can't open input  `default': snd_pcm_open error: Device or resource busy

When fails, and i stop MM, work correctly (same with arecord):
pi@magicpiHost:~ $ rec test.wav

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:04.69 [00:00:00.00] Out:221k  [      |      ]        Clip:0   

What could I send you?

Regards!

**Comment by eouia** [comment] 2019-02-06 15:16
>When the error appear i try in another console:
pi@magicpiHost:~ $ rec test.wav
rec FAIL formats: can't open input `default': snd_pcm_open error: Device or resource busy

I think this is important. What commands did you done before error?

And If you are using `pm2` stop it(`pm2 stop mm`), then execute MM with `npm start dev` on MM directory. You can get some logs or messages on your terminal shell.

**Comment by idmarco** [comment] 2019-02-07 11:19
Hi!
I tested again after reboot. I dont execute nothing and then i try run MM with npm start dev.
I test with my hotword 2 times, and then i get the error.

I attach the output log and the console log.
Thanks!!
[out.log](https://github.com/eouia/MMM-AssistantMk2/files/2840510/out.log)
[0.0.0.0-1549538014620.log](https://github.com/eouia/MMM-AssistantMk2/files/2840511/0.0.0.0-1549538014620.log)

**Comment by eouia** [comment] 2019-02-07 11:30
It seems your mic has problem on log.
To make things simple, Could you disable all modules except MMM-Hotword? (even disable MMM-AssistantMk2 also)
Check MMM-Hotword working with your mic. 
After confirmation of MMM-Hotword working, we can progress to MMM-AssistantMk2.

:: Your logs says that error happened on very early stage, even though MMM-Hotword or MMM-AssistantMk2 not being ready. So I cannot guess where the error comes at this moment, that is why we should drop many possible reasons one by one.

**Comment by idmarco** [comment] 2019-02-07 11:47
I disabled all modules except Hotword and MMM-AssistantMk2 (because i cant test it without that module). Works well one or two times.
Attach the logs and config file.
Regards!
[0.0.0.0-1549539623419.log](https://github.com/eouia/MMM-AssistantMk2/files/2840601/0.0.0.0-1549539623419.log)
[out.log](https://github.com/eouia/MMM-AssistantMk2/files/2840602/out.log)

[config.js.txt](https://github.com/eouia/MMM-AssistantMk2/files/2840607/config.js.txt)

**Comment by eouia** [comment] 2019-02-07 12:15
For more detailed information, set configuration like this;
- For MMM-AssistantMk2 :
```
{
      module: "MMM-AssistantMk2",
      position: "lower_third",
      config: {
        verbose: true,
```
- For MMM-Hotword;
```
{
      module: "MMM-Hotword",
      config: {
        testMic: true,
```

Now the log will shows more details.

**Comment by idmarco** [comment] 2019-02-07 12:34
Its very very strange, because with that properties, i test it and not fail ¿?
Attach the files.

Thanks!
[out.log](https://github.com/eouia/MMM-AssistantMk2/files/2840806/out.log)
[config.js.txt](https://github.com/eouia/MMM-AssistantMk2/files/2840807/config.js.txt)

**Comment by eouia** [comment] 2019-02-07 12:38
Those properties do just printout some values. I feel also weird about your symptoms.
Anyway, it seems working now.

**Comment by idmarco** [comment] 2019-02-07 13:00
Thanks. I test more and I advice you.
Can I ask you some questions? I do not know if it's the right place.
1- I have to wait until the hotword recognizes my keyword to ask the question to GA. Is it because of snowbro?
2- I cant stop the answer even if I say my hotword

Thanks for all!

**Comment by eouia** [comment] 2019-02-07 13:13
1. I'm using `Google Assistant SDK service for device` to implement this module. The SDK doesn't have hotword detection as default. So I should add MMM-Hotword to make that features.
Another library `Google Assistant SDK library for device` has that feature by default, but it has lack of some other features and it is made with python. I should have selected one of both to make this module. I chose `SDK service` instead `SKD library`
Anyway, that is why MMM-Hotword is needed.

2. During response, MMM-Hotword is paused. After finishing response, MMM-Hotword will be resumed.
There are two reason for this;
- If MMM-Hotword still be listening during responsing, the response itself could be detected as hotword. It could make unintended misbehaviors.
- hotword detecting consumes CPU power, Always listening could make somewhat RPI slowly, it could make response sound so choppy or slow.

**Comment by idmarco** [comment] 2019-02-07 13:57
It´s possible not stop MMM-Hotword?
When I could make some test, i write you!
Thanks for all sir!

**Comment by eouia** [comment] 2019-02-07 14:02
But MMM-Hotword and MMM-AssistantMk2 use same Mic. on RPI, without mixer, two application cannot occupy same mic device at a same time.

**Comment by idmarco** [comment] 2019-02-07 14:15
Ok! I understand you. I will test Assistant a lot and tomorrow I advice you.
Thanks!!!

**Comment by idmarco** [comment] 2019-02-08 09:11
Now works fine. But I think that i cant use it because i use mopidy  in my raspberry and if the music is playing or pause, an error appear and i need reboot MM :(
[HOTWORD] stops listening
End Recording: 8590.426ms
Speaker error: 1
Whoops! There was an uncaught exception...
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Any idea?
Thanks!

**Comment by eouia** [comment] 2019-02-08 09:46
Unlike other PC class devices, RPI(And the Raspbian) is not so smart.
The problem is, The default setup of mixer of Raspbian on RPI allows one device to be occupied by one  application, So multi-outputs cannot be mixed by default.
To avoid collision, you should stop your mopidy before AMK2 be using the speaker device after hotword detection. and resume after AMK2 response. You can use HOTWORD_DETECTED 
 and ASSISTANT_DEACTIVATED notifications to catch the start and end.
Or you should find a way to mix multi-outputs. I think it could be possible ideally, but I'm not that kind of expert so have no idea about it. I can't help.

**Comment by eouia** [comment] 2019-02-24 13:45
I'll close this issue there is no more feedback about this. Wish a good luck.

**Closed by eouia** 2019-02-24 13:45 UTC
